### ISSUE TITLE
Application relogins after logout when Aviation SSO is integrated

### ISSUE THREAD

**Issue by akpx** [PredixDev/px-login#10] opened 2016-06-10 13:04 UTC
## Expected behavior

On clicking Logout link, the user should get logged out and session should be terminated with UI redirected to SSO Login page
## Actual behavior

Once application has logged out, it re-logins automatically and shows the application page
## Steps to reproduce the problem:

Integrate application with GE SSO UAA, 
Click on logout link.
The application logs out and the re-logs in
## Environment (_component version number, Browser (including version), operating system, hardware, etc_):

All browsers, using GE Aviation SSO UAA

**Comment by mdwragg** [comment] 2016-06-10 15:58
Hi, thanks for taking the time to raise this issue!

Can you please provide us with an example so we can recreate this issue? We don't have knowledge of the environment you are having issues with. A codepen or gist would be helpful.

https://codepen.io/mdwragg/pen/oLbMwJ

Thanks,
Martin.

**Comment by papscript** [comment] 2016-09-01 07:23
Do you found any working solution for that? 
The problem is correlated with the one described at predix forum https://forum.predix.io/questions/7420/uaa-sso-logout-functionality-not-working.html

**Comment by kentcabarle** [comment] 2017-03-10 09:27
Any updates for the fix for this? I'm also encountering the issue.. 
Answers under https://forum.predix.io/questions/7420/uaa-sso-logout-functionality-not-working.html did not work. :(

**Comment by papscript** [comment] 2017-03-11 13:07
Which instance of UAA SSO do you use, test or prod? Also do you destroy session after logout and redirect properly?

**Comment by kentcabarle** [comment] 2017-03-13 02:09
I'm using shared uaa select, allowed-provider = ["ge-sso-prod"].
![shared-uaa](https://cloud.githubusercontent.com/assets/25141204/23838855/b6ccb336-07d4-11e7-9af8-6d9a590b2be3.PNG)

Yes, it's already included in the app.js of predix seed. Code snippet below.

//logout route
app.get('/logout', function(req, res) {
	req.session.destroy();
	req.logout();
	passportConfig.reset(); //reset auth tokens
	res.redirect(config.uaaURL + '/logout?redirect=' + config.appURL);
});

**Comment by kentcabarle** [comment] 2017-03-13 08:29
Just an update, I tried this one: "Answer by Ben Sykes · Aug 30, 2016 at 10:04 AM" from "https://forum.predix.io/questions/7420/uaa-sso-logout-functionality-not-working.html" and it actually worked. My bad. Thank you!

**Comment by akpx** [comment] 2017-03-14 07:09
**https://forum.predix.io/questions/7420/uaa-sso-logout-functionality-not-working.html**

works fine

**Closed as completed** 2017-03-14 07:08 UTC
Labels: bug
